import { ShopConfig, Product } from '../types.js';

export const BRAND_CONSTANTS = {
  SHOP_NAME: 'Aura Mart',
  SHOP_SHORT_NAME: 'Aura',
  TAGLINE: 'Daily Groceries & Fashion Jewellery',
  HERO_HEADING: 'Essentials & Elegance, Under One Roof',
  HERO_DESCRIPTION:
    "Your one-stop destination for daily kirana staples, household essentials, and beautiful fashion jewellery. Discover everyday quality and style at unbeatable prices.",
  MONOGRAM: 'AM',
  CURRENCY: '₹',
  WHATSAPP_NUMBER: '919876543210',
  WHATSAPP_PREFILL: 'Hello Aura Mart, I would like to inquire about',
  WHATSAPP_BUTTON_TEXT: 'Ask on WhatsApp',
  WHATSAPP_RATE_TEXT: 'Ask Price',
  ADDRESS: 'Shop No. 4 & 5, Main Market',
  CITY: 'Jaipur, Rajasthan',
  TIMINGS: 'Mon - Sun: 9:00 AM – 9:00 PM',
  KIRANA_TAB_LABEL: 'Kirana',
  JEWELLERY_TAB_LABEL: 'Imitation Jewellery',
} as const;

export const DEFAULT_KIRANA_CATEGORIES: string[] = [
  'Atta, Dal & Rice',
  'Tel & Desi Ghee',
  'Masale & Spices',
  'Chai, Cheeni & Dry Fruits',
  'Daily Snacks',
  'Household & Puja',
];

export const DEFAULT_JEWELLERY_CATEGORIES: string[] = [
  'Gold & Silver Coins',
  'Silver Payal & Bichhiya',
  'Traditional Bangles & Kada',
  'Necklace & Mangalsutra',
  'Jhumkas & Earrings',
  'Fashion & Daily Wear',
];

export const ALL_DEFAULT_CATEGORIES: string[] = [
  ...DEFAULT_KIRANA_CATEGORIES,
  ...DEFAULT_JEWELLERY_CATEGORIES,
];

export const DEFAULT_SHOP_CONFIG: ShopConfig = {
  shopName: BRAND_CONSTANTS.SHOP_NAME,
  tagline: BRAND_CONSTANTS.TAGLINE,
  description: BRAND_CONSTANTS.HERO_DESCRIPTION,
  logoMonogram: BRAND_CONSTANTS.MONOGRAM,
  currency: BRAND_CONSTANTS.CURRENCY,
  whatsappNumber: BRAND_CONSTANTS.WHATSAPP_NUMBER,
  whatsappPreFill: BRAND_CONSTANTS.WHATSAPP_PREFILL,
  address: BRAND_CONSTANTS.ADDRESS,
  city: BRAND_CONSTANTS.CITY,
  timings: BRAND_CONSTANTS.TIMINGS,
  categories: ALL_DEFAULT_CATEGORIES,
};

export const INITIAL_REALISTIC_PRODUCTS: Product[] = [
  // 6 Kirana Items
  {
    id: 'prod-k1',
    name: 'Sharbati MP Gehu Atta (Freshly Ground)',
    department: 'Kirana',
    category: 'Atta, Dal & Rice',
    unit: 'per 5 kg bag',
    price: 260,
    originalPrice: 290,
    description: '100% pure Madhya Pradesh Sharbati wheat flour, freshly stone-ground daily. Makes extra soft, golden rotis with natural wheat sweetness.',
    imageUrl: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=800&q=80',
    inStock: true,
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: 'prod-k2',
    name: 'Royal Aged Basmati Rice (Daawat Dubar)',
    department: 'Kirana',
    category: 'Atta, Dal & Rice',
    unit: 'per kg',
    price: 135,
    originalPrice: 155,
    description: 'Two-year aged aromatic slender basmati rice. Cooked grains extend to twice their size. Ideal for fragrant pulao and festive family meals.',
    imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=800&q=80',
    inStock: true,
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: 'prod-k3',
    name: 'Pure Desi Cow Ghee (Vedic Bilona Method)',
    department: 'Kirana',
    category: 'Tel & Desi Ghee',
    unit: 'per 1 litre tin',
    price: 720,
    originalPrice: 780,
    description: 'Traditional village bilona cow ghee with authentic granular texture and nutty fragrance. Untouched by chemicals, perfect for tadka and puja.',
    imageUrl: 'https://images.unsplash.com/photo-1631451095765-2c91616fc9e6?auto=format&fit=crop&w=800&q=80',
    inStock: true,
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: 'prod-k4',
    name: 'Kashmiri Kesar & Green Cardamom Spices Pack',
    department: 'Kirana',
    category: 'Masale & Spices',
    unit: 'per box',
    price: 380,
    description: 'Hand-picked fragrant 8mm bold green cardamom pods paired with pure Grade-A Mongra Kashmiri saffron strands for traditional kheer and sweets.',
    imageUrl: 'https://images.unsplash.com/photo-1599940824399-b87987ceb72a?auto=format&fit=crop&w=800&q=80',
    inStock: true,
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: 'prod-k5',
    name: 'Jumbo California Badam & Afghani Kaju Mix',
    department: 'Kirana',
    category: 'Chai, Cheeni & Dry Fruits',
    unit: 'per 500g pack',
    price: 540,
    originalPrice: 620,
    description: 'Crunchy whole California almonds and whole W-240 white cashews. Packed fresh under vacuum seal to ensure peak nutrition.',
    imageUrl: 'https://images.unsplash.com/photo-1508061252224-237ff54ed5a9?auto=format&fit=crop&w=800&q=80',
    inStock: true,
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: 'prod-k6',
    name: 'Special CTC Kadak Masala Chai Patti',
    department: 'Kirana',
    category: 'Chai, Cheeni & Dry Fruits',
    unit: 'per 500g packet',
    price: 240,
    description: 'Strong Upper Assam CTC tea leaves gently blended with crushed dried ginger, holy basil, and cinnamon for a refreshing morning kick.',
    imageUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=800&q=80',
    inStock: true,
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },

  // 6 Jewellery Items
  {
    id: 'prod-j1',
    name: '925 Pure Silver Ghungroo Payal (Pair)',
    department: 'Jewellery',
    category: 'Silver Payal & Bichhiya',
    unit: 'per pair',
    price: 2850,
    originalPrice: 3200,
    description: 'Certified 92.5 hallmark pure silver traditional bridal anklets with melodious small ghungroo bells. Anti-tarnish rhodium coating for daily wear.',
    imageUrl: 'https://images.unsplash.com/photo-1611591475152-478311383af8?auto=format&fit=crop&w=800&q=80',
    inStock: true,
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: 'prod-j2',
    name: '24K Pure Gold Lakshmi Ganesh Bullion Coin (5g)',
    department: 'Jewellery',
    category: 'Gold & Silver Coins',
    unit: 'per 5g coin',
    price: 0,
    priceOnRequest: true,
    description: '999 purity certified 24 Karat gold coin embossed with auspicious Lakshmi Ganesh motifs. Sealed in tamper-proof certicard. Rates change daily—inquire on WhatsApp.',
    imageUrl: 'https://images.unsplash.com/photo-1610375461246-83df859d849d?auto=format&fit=crop&w=800&q=80',
    inStock: true,
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: 'prod-j3',
    name: 'Traditional Rajasthani Gold-Plated Filigree Kada (Set of 2)',
    department: 'Jewellery',
    category: 'Traditional Bangles & Kada',
    unit: 'per set of 2',
    price: 1450,
    originalPrice: 1750,
    description: 'Hand-carved Rajasthani royal filigree bangles with micro gold polish and secure side screw lock. Rust-proof and skin-safe brass base.',
    imageUrl: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=80',
    inStock: true,
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: 'prod-j4',
    name: '22K Gold Antique Matte Temple Choker Necklace',
    department: 'Jewellery',
    category: 'Necklace & Mangalsutra',
    unit: 'per piece',
    price: 0,
    priceOnRequest: true,
    description: "Heritage temple jewellery choker featuring Goddess Lakshmi motif bordered with red kemp stones and golden jhumki drops. Contact on WhatsApp for today's gold rate and customization.",
    imageUrl: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80',
    inStock: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-j5',
    name: 'Polki Kundan & Seed Pearl Festive Jhumkas',
    department: 'Jewellery',
    category: 'Jhumkas & Earrings',
    unit: 'per pair',
    price: 950,
    originalPrice: 1200,
    description: 'Festive crescent moon ear danglers studded with brilliant white polki stones and tiny ivory seed pearls. Lightweight push-back fitting.',
    imageUrl: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=800&q=80',
    inStock: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-j6',
    name: 'Solid Silver 925 Peacock Toe Rings / Bichhiya (Set of 2)',
    department: 'Jewellery',
    category: 'Silver Payal & Bichhiya',
    unit: 'per pair',
    price: 650,
    description: 'Hallmarked 92.5 pure silver adjustable toe rings etched with traditional peacock plumage. Smooth polished edges for daily comfortable wear.',
    imageUrl: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=800&q=80',
    inStock: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
